global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'application_status'
    metrics_path: /health
    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
